export const isProxySymbol = Symbol('merkling/isProxy')
export const isIpldNodeSymbol = Symbol('merkling/isIpldNode')
export const isDirtySymbol = Symbol('merkling/isDirty')
export const getStateSymbol = Symbol('merkling/getState')
export const setCidSymbol = Symbol('merkling/setCid')
export const getCidSymbol = Symbol('merkling/getCid')
